### ISSUE TITLE
Suggestion docs redirected to this readme

### ISSUE THREAD

**Issue by MintPlayer** [dewitt/opensearch#20]
The url http://www.opensearch.org/Specifications/OpenSearch/Extensions/Suggestions/1.1 that's being referenced in this document is being redirected back to this page.

**Comment by dewitt** [comment]
Good catch. The old opensearch.org site is now redirecting to github, but that particular wiki page didn't get hand-converted to markdown yet, so it just redirects to the top-level (this page).

I can edit the spec to point to https://github.com/dewitt/opensearch/blob/master/mediawiki/Specifications/OpenSearch/Extensions/Suggestions/1.1/Draft%201.wiki instead, so at least it goes somewhere useful.
