### ISSUE TITLE
Distinguish from the "OpenSearch" branded fork of Elasticsearch

### ISSUE THREAD

**Issue by marclaporte** [dewitt/opensearch#32]
We now have 2:
- https://en.wikipedia.org/wiki/OpenSearch
- https://en.wikipedia.org/wiki/OpenSearch_(software)

**Comment by alcinnz** [comment]
Yes, this is a real problem in the eyes of standards organizations I'm involved with. Leads some members to assume that OpenSearch is "legacy". Also there's now a [Open Search Foundation](https://opensearchfoundation.org/) I at first thought was you.

P.S. I'm a big fan of your work! It got me into developing web browsers so I could have one with OpenSearch+RSS/ATOM support builtin, but unfortunately there's a lot of distractions to find in that realm.

**Comment by dewitt** [comment]
Thanks, all! I updated the [README](https://github.com/dewitt/opensearch/blob/master/README.md) to add some clarifying text distinguishing the multiple uses of the term "Open Search".
